services:
  app:
    build: .
    command: sh -c "pnpm install && pnpm --filter @thesis/client run build && pnpm --filter @thesis/server run start"
    ports:
      - 127.0.0.1:3000:443
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    container_name: test_db
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
    - ${MYSQL_PORT}:3306
    restart: always
    security_opt:
    - seccomp:unconfined
    environment:
    - MYSQL_DATABASE=${MYSQL_DB}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8890:80
    environment:
        PMA_HOST: test_db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
        UPLOAD_LIMIT: 20000000000
        MAX_EXECUTION_TIME: 1500