export const KLASSEN_QUERY_KEY = 'klassen'
export const SCHUELER_QUERY_KEY = 'schueler'
export const GANZTAGSANGEBOT_QUERY_KEY = 'ganztagsangebot'
export const DIAGNOSTIKEN_QUERY_KEY = 'diagnostik'
export const ANWESENHEITEN_QUERY_KEY = 'anwesenheiten'
export const NACHRICHTEN_QUERY_KEY = 'nachrichten'