/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as IndexImport } from './routes/index'
import { Route as authRegisterIndexImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as appSettingsIndexImport } from './routes/(app)/settings/index'
import { Route as appSchuelerIndexImport } from './routes/(app)/schueler/index'
import { Route as appRollenmanagementIndexImport } from './routes/(app)/rollenmanagement/index'
import { Route as appResetPasswordIndexImport } from './routes/(app)/reset-password/index'
import { Route as appKlassenIndexImport } from './routes/(app)/klassen/index'
import { Route as appGanztagsangeboteIndexImport } from './routes/(app)/ganztagsangebote/index'
import { Route as appDiagnostikverfahrenIndexImport } from './routes/(app)/diagnostikverfahren/index'
import { Route as appSchuelerSchuelerIdIndexImport } from './routes/(app)/schueler/$schuelerId/index'
import { Route as appKlassenKlassenIdIndexImport } from './routes/(app)/klassen/$klassenId/index'
import { Route as appGanztagsangeboteGanztagsangebotIdIndexImport } from './routes/(app)/ganztagsangebote/$ganztagsangebotId/index'
import { Route as appDiagnostikverfahrenDiagnostikIdIndexImport } from './routes/(app)/diagnostikverfahren/$diagnostikId/index'
import { Route as appSchuelerSchuelerIdMonitoringImport } from './routes/(app)/schueler/$schuelerId/monitoring'
import { Route as appSchuelerSchuelerIdHistorieImport } from './routes/(app)/schueler/$schuelerId/historie'
import { Route as appSchuelerSchuelerIdBrettImport } from './routes/(app)/schueler/$schuelerId/brett'
import { Route as appSchuelerSchuelerIdAnwesenheitenImport } from './routes/(app)/schueler/$schuelerId/anwesenheiten'
import { Route as appKlassenKlassenIdTestsImport } from './routes/(app)/klassen/$klassenId/tests'
import { Route as appKlassenKlassenIdEditImport } from './routes/(app)/klassen/$klassenId/edit'
import { Route as appKlassenKlassenIdBrettImport } from './routes/(app)/klassen/$klassenId/brett'
import { Route as appGanztagsangeboteGanztagsangebotIdEditImport } from './routes/(app)/ganztagsangebote/$ganztagsangebotId/edit'

// Create/Update Routes

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterIndexRoute = authRegisterIndexImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const appSettingsIndexRoute = appSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)

const appSchuelerIndexRoute = appSchuelerIndexImport.update({
  id: '/schueler/',
  path: '/schueler/',
  getParentRoute: () => appRouteRoute,
} as any)

const appRollenmanagementIndexRoute = appRollenmanagementIndexImport.update({
  id: '/rollenmanagement/',
  path: '/rollenmanagement/',
  getParentRoute: () => appRouteRoute,
} as any)

const appResetPasswordIndexRoute = appResetPasswordIndexImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => appRouteRoute,
} as any)

const appKlassenIndexRoute = appKlassenIndexImport.update({
  id: '/klassen/',
  path: '/klassen/',
  getParentRoute: () => appRouteRoute,
} as any)

const appGanztagsangeboteIndexRoute = appGanztagsangeboteIndexImport.update({
  id: '/ganztagsangebote/',
  path: '/ganztagsangebote/',
  getParentRoute: () => appRouteRoute,
} as any)

const appDiagnostikverfahrenIndexRoute =
  appDiagnostikverfahrenIndexImport.update({
    id: '/diagnostikverfahren/',
    path: '/diagnostikverfahren/',
    getParentRoute: () => appRouteRoute,
  } as any)

const appSchuelerSchuelerIdIndexRoute = appSchuelerSchuelerIdIndexImport.update(
  {
    id: '/schueler/$schuelerId/',
    path: '/schueler/$schuelerId/',
    getParentRoute: () => appRouteRoute,
  } as any,
)

const appKlassenKlassenIdIndexRoute = appKlassenKlassenIdIndexImport.update({
  id: '/klassen/$klassenId/',
  path: '/klassen/$klassenId/',
  getParentRoute: () => appRouteRoute,
} as any)

const appGanztagsangeboteGanztagsangebotIdIndexRoute =
  appGanztagsangeboteGanztagsangebotIdIndexImport.update({
    id: '/ganztagsangebote/$ganztagsangebotId/',
    path: '/ganztagsangebote/$ganztagsangebotId/',
    getParentRoute: () => appRouteRoute,
  } as any)

const appDiagnostikverfahrenDiagnostikIdIndexRoute =
  appDiagnostikverfahrenDiagnostikIdIndexImport.update({
    id: '/diagnostikverfahren/$diagnostikId/',
    path: '/diagnostikverfahren/$diagnostikId/',
    getParentRoute: () => appRouteRoute,
  } as any)

const appSchuelerSchuelerIdMonitoringRoute =
  appSchuelerSchuelerIdMonitoringImport.update({
    id: '/schueler/$schuelerId/monitoring',
    path: '/schueler/$schuelerId/monitoring',
    getParentRoute: () => appRouteRoute,
  } as any)

const appSchuelerSchuelerIdHistorieRoute =
  appSchuelerSchuelerIdHistorieImport.update({
    id: '/schueler/$schuelerId/historie',
    path: '/schueler/$schuelerId/historie',
    getParentRoute: () => appRouteRoute,
  } as any)

const appSchuelerSchuelerIdBrettRoute = appSchuelerSchuelerIdBrettImport.update(
  {
    id: '/schueler/$schuelerId/brett',
    path: '/schueler/$schuelerId/brett',
    getParentRoute: () => appRouteRoute,
  } as any,
)

const appSchuelerSchuelerIdAnwesenheitenRoute =
  appSchuelerSchuelerIdAnwesenheitenImport.update({
    id: '/schueler/$schuelerId/anwesenheiten',
    path: '/schueler/$schuelerId/anwesenheiten',
    getParentRoute: () => appRouteRoute,
  } as any)

const appKlassenKlassenIdTestsRoute = appKlassenKlassenIdTestsImport.update({
  id: '/klassen/$klassenId/tests',
  path: '/klassen/$klassenId/tests',
  getParentRoute: () => appRouteRoute,
} as any)

const appKlassenKlassenIdEditRoute = appKlassenKlassenIdEditImport.update({
  id: '/klassen/$klassenId/edit',
  path: '/klassen/$klassenId/edit',
  getParentRoute: () => appRouteRoute,
} as any)

const appKlassenKlassenIdBrettRoute = appKlassenKlassenIdBrettImport.update({
  id: '/klassen/$klassenId/brett',
  path: '/klassen/$klassenId/brett',
  getParentRoute: () => appRouteRoute,
} as any)

const appGanztagsangeboteGanztagsangebotIdEditRoute =
  appGanztagsangeboteGanztagsangebotIdEditImport.update({
    id: '/ganztagsangebote/$ganztagsangebotId/edit',
    path: '/ganztagsangebote/$ganztagsangebotId/edit',
    getParentRoute: () => appRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/diagnostikverfahren/': {
      id: '/(app)/diagnostikverfahren/'
      path: '/diagnostikverfahren'
      fullPath: '/diagnostikverfahren'
      preLoaderRoute: typeof appDiagnostikverfahrenIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/ganztagsangebote/': {
      id: '/(app)/ganztagsangebote/'
      path: '/ganztagsangebote'
      fullPath: '/ganztagsangebote'
      preLoaderRoute: typeof appGanztagsangeboteIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/klassen/': {
      id: '/(app)/klassen/'
      path: '/klassen'
      fullPath: '/klassen'
      preLoaderRoute: typeof appKlassenIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/reset-password/': {
      id: '/(app)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof appResetPasswordIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/rollenmanagement/': {
      id: '/(app)/rollenmanagement/'
      path: '/rollenmanagement'
      fullPath: '/rollenmanagement'
      preLoaderRoute: typeof appRollenmanagementIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/schueler/': {
      id: '/(app)/schueler/'
      path: '/schueler'
      fullPath: '/schueler'
      preLoaderRoute: typeof appSchuelerIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/ganztagsangebote/$ganztagsangebotId/edit': {
      id: '/(app)/ganztagsangebote/$ganztagsangebotId/edit'
      path: '/ganztagsangebote/$ganztagsangebotId/edit'
      fullPath: '/ganztagsangebote/$ganztagsangebotId/edit'
      preLoaderRoute: typeof appGanztagsangeboteGanztagsangebotIdEditImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/klassen/$klassenId/brett': {
      id: '/(app)/klassen/$klassenId/brett'
      path: '/klassen/$klassenId/brett'
      fullPath: '/klassen/$klassenId/brett'
      preLoaderRoute: typeof appKlassenKlassenIdBrettImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/klassen/$klassenId/edit': {
      id: '/(app)/klassen/$klassenId/edit'
      path: '/klassen/$klassenId/edit'
      fullPath: '/klassen/$klassenId/edit'
      preLoaderRoute: typeof appKlassenKlassenIdEditImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/klassen/$klassenId/tests': {
      id: '/(app)/klassen/$klassenId/tests'
      path: '/klassen/$klassenId/tests'
      fullPath: '/klassen/$klassenId/tests'
      preLoaderRoute: typeof appKlassenKlassenIdTestsImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/schueler/$schuelerId/anwesenheiten': {
      id: '/(app)/schueler/$schuelerId/anwesenheiten'
      path: '/schueler/$schuelerId/anwesenheiten'
      fullPath: '/schueler/$schuelerId/anwesenheiten'
      preLoaderRoute: typeof appSchuelerSchuelerIdAnwesenheitenImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/schueler/$schuelerId/brett': {
      id: '/(app)/schueler/$schuelerId/brett'
      path: '/schueler/$schuelerId/brett'
      fullPath: '/schueler/$schuelerId/brett'
      preLoaderRoute: typeof appSchuelerSchuelerIdBrettImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/schueler/$schuelerId/historie': {
      id: '/(app)/schueler/$schuelerId/historie'
      path: '/schueler/$schuelerId/historie'
      fullPath: '/schueler/$schuelerId/historie'
      preLoaderRoute: typeof appSchuelerSchuelerIdHistorieImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/schueler/$schuelerId/monitoring': {
      id: '/(app)/schueler/$schuelerId/monitoring'
      path: '/schueler/$schuelerId/monitoring'
      fullPath: '/schueler/$schuelerId/monitoring'
      preLoaderRoute: typeof appSchuelerSchuelerIdMonitoringImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/diagnostikverfahren/$diagnostikId/': {
      id: '/(app)/diagnostikverfahren/$diagnostikId/'
      path: '/diagnostikverfahren/$diagnostikId'
      fullPath: '/diagnostikverfahren/$diagnostikId'
      preLoaderRoute: typeof appDiagnostikverfahrenDiagnostikIdIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/ganztagsangebote/$ganztagsangebotId/': {
      id: '/(app)/ganztagsangebote/$ganztagsangebotId/'
      path: '/ganztagsangebote/$ganztagsangebotId'
      fullPath: '/ganztagsangebote/$ganztagsangebotId'
      preLoaderRoute: typeof appGanztagsangeboteGanztagsangebotIdIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/klassen/$klassenId/': {
      id: '/(app)/klassen/$klassenId/'
      path: '/klassen/$klassenId'
      fullPath: '/klassen/$klassenId'
      preLoaderRoute: typeof appKlassenKlassenIdIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/schueler/$schuelerId/': {
      id: '/(app)/schueler/$schuelerId/'
      path: '/schueler/$schuelerId'
      fullPath: '/schueler/$schuelerId'
      preLoaderRoute: typeof appSchuelerSchuelerIdIndexImport
      parentRoute: typeof appRouteImport
    }
  }
}

// Create and export the route tree

interface appRouteRouteChildren {
  appDiagnostikverfahrenIndexRoute: typeof appDiagnostikverfahrenIndexRoute
  appGanztagsangeboteIndexRoute: typeof appGanztagsangeboteIndexRoute
  appKlassenIndexRoute: typeof appKlassenIndexRoute
  appResetPasswordIndexRoute: typeof appResetPasswordIndexRoute
  appRollenmanagementIndexRoute: typeof appRollenmanagementIndexRoute
  appSchuelerIndexRoute: typeof appSchuelerIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  appGanztagsangeboteGanztagsangebotIdEditRoute: typeof appGanztagsangeboteGanztagsangebotIdEditRoute
  appKlassenKlassenIdBrettRoute: typeof appKlassenKlassenIdBrettRoute
  appKlassenKlassenIdEditRoute: typeof appKlassenKlassenIdEditRoute
  appKlassenKlassenIdTestsRoute: typeof appKlassenKlassenIdTestsRoute
  appSchuelerSchuelerIdAnwesenheitenRoute: typeof appSchuelerSchuelerIdAnwesenheitenRoute
  appSchuelerSchuelerIdBrettRoute: typeof appSchuelerSchuelerIdBrettRoute
  appSchuelerSchuelerIdHistorieRoute: typeof appSchuelerSchuelerIdHistorieRoute
  appSchuelerSchuelerIdMonitoringRoute: typeof appSchuelerSchuelerIdMonitoringRoute
  appDiagnostikverfahrenDiagnostikIdIndexRoute: typeof appDiagnostikverfahrenDiagnostikIdIndexRoute
  appGanztagsangeboteGanztagsangebotIdIndexRoute: typeof appGanztagsangeboteGanztagsangebotIdIndexRoute
  appKlassenKlassenIdIndexRoute: typeof appKlassenKlassenIdIndexRoute
  appSchuelerSchuelerIdIndexRoute: typeof appSchuelerSchuelerIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDiagnostikverfahrenIndexRoute: appDiagnostikverfahrenIndexRoute,
  appGanztagsangeboteIndexRoute: appGanztagsangeboteIndexRoute,
  appKlassenIndexRoute: appKlassenIndexRoute,
  appResetPasswordIndexRoute: appResetPasswordIndexRoute,
  appRollenmanagementIndexRoute: appRollenmanagementIndexRoute,
  appSchuelerIndexRoute: appSchuelerIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  appGanztagsangeboteGanztagsangebotIdEditRoute:
    appGanztagsangeboteGanztagsangebotIdEditRoute,
  appKlassenKlassenIdBrettRoute: appKlassenKlassenIdBrettRoute,
  appKlassenKlassenIdEditRoute: appKlassenKlassenIdEditRoute,
  appKlassenKlassenIdTestsRoute: appKlassenKlassenIdTestsRoute,
  appSchuelerSchuelerIdAnwesenheitenRoute:
    appSchuelerSchuelerIdAnwesenheitenRoute,
  appSchuelerSchuelerIdBrettRoute: appSchuelerSchuelerIdBrettRoute,
  appSchuelerSchuelerIdHistorieRoute: appSchuelerSchuelerIdHistorieRoute,
  appSchuelerSchuelerIdMonitoringRoute: appSchuelerSchuelerIdMonitoringRoute,
  appDiagnostikverfahrenDiagnostikIdIndexRoute:
    appDiagnostikverfahrenDiagnostikIdIndexRoute,
  appGanztagsangeboteGanztagsangebotIdIndexRoute:
    appGanztagsangeboteGanztagsangebotIdIndexRoute,
  appKlassenKlassenIdIndexRoute: appKlassenKlassenIdIndexRoute,
  appSchuelerSchuelerIdIndexRoute: appSchuelerSchuelerIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appRouteRouteWithChildren
  '/diagnostikverfahren': typeof appDiagnostikverfahrenIndexRoute
  '/ganztagsangebote': typeof appGanztagsangeboteIndexRoute
  '/klassen': typeof appKlassenIndexRoute
  '/reset-password': typeof appResetPasswordIndexRoute
  '/rollenmanagement': typeof appRollenmanagementIndexRoute
  '/schueler': typeof appSchuelerIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/ganztagsangebote/$ganztagsangebotId/edit': typeof appGanztagsangeboteGanztagsangebotIdEditRoute
  '/klassen/$klassenId/brett': typeof appKlassenKlassenIdBrettRoute
  '/klassen/$klassenId/edit': typeof appKlassenKlassenIdEditRoute
  '/klassen/$klassenId/tests': typeof appKlassenKlassenIdTestsRoute
  '/schueler/$schuelerId/anwesenheiten': typeof appSchuelerSchuelerIdAnwesenheitenRoute
  '/schueler/$schuelerId/brett': typeof appSchuelerSchuelerIdBrettRoute
  '/schueler/$schuelerId/historie': typeof appSchuelerSchuelerIdHistorieRoute
  '/schueler/$schuelerId/monitoring': typeof appSchuelerSchuelerIdMonitoringRoute
  '/diagnostikverfahren/$diagnostikId': typeof appDiagnostikverfahrenDiagnostikIdIndexRoute
  '/ganztagsangebote/$ganztagsangebotId': typeof appGanztagsangeboteGanztagsangebotIdIndexRoute
  '/klassen/$klassenId': typeof appKlassenKlassenIdIndexRoute
  '/schueler/$schuelerId': typeof appSchuelerSchuelerIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appRouteRouteWithChildren
  '/diagnostikverfahren': typeof appDiagnostikverfahrenIndexRoute
  '/ganztagsangebote': typeof appGanztagsangeboteIndexRoute
  '/klassen': typeof appKlassenIndexRoute
  '/reset-password': typeof appResetPasswordIndexRoute
  '/rollenmanagement': typeof appRollenmanagementIndexRoute
  '/schueler': typeof appSchuelerIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/ganztagsangebote/$ganztagsangebotId/edit': typeof appGanztagsangeboteGanztagsangebotIdEditRoute
  '/klassen/$klassenId/brett': typeof appKlassenKlassenIdBrettRoute
  '/klassen/$klassenId/edit': typeof appKlassenKlassenIdEditRoute
  '/klassen/$klassenId/tests': typeof appKlassenKlassenIdTestsRoute
  '/schueler/$schuelerId/anwesenheiten': typeof appSchuelerSchuelerIdAnwesenheitenRoute
  '/schueler/$schuelerId/brett': typeof appSchuelerSchuelerIdBrettRoute
  '/schueler/$schuelerId/historie': typeof appSchuelerSchuelerIdHistorieRoute
  '/schueler/$schuelerId/monitoring': typeof appSchuelerSchuelerIdMonitoringRoute
  '/diagnostikverfahren/$diagnostikId': typeof appDiagnostikverfahrenDiagnostikIdIndexRoute
  '/ganztagsangebote/$ganztagsangebotId': typeof appGanztagsangeboteGanztagsangebotIdIndexRoute
  '/klassen/$klassenId': typeof appKlassenKlassenIdIndexRoute
  '/schueler/$schuelerId': typeof appSchuelerSchuelerIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/diagnostikverfahren/': typeof appDiagnostikverfahrenIndexRoute
  '/(app)/ganztagsangebote/': typeof appGanztagsangeboteIndexRoute
  '/(app)/klassen/': typeof appKlassenIndexRoute
  '/(app)/reset-password/': typeof appResetPasswordIndexRoute
  '/(app)/rollenmanagement/': typeof appRollenmanagementIndexRoute
  '/(app)/schueler/': typeof appSchuelerIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(app)/ganztagsangebote/$ganztagsangebotId/edit': typeof appGanztagsangeboteGanztagsangebotIdEditRoute
  '/(app)/klassen/$klassenId/brett': typeof appKlassenKlassenIdBrettRoute
  '/(app)/klassen/$klassenId/edit': typeof appKlassenKlassenIdEditRoute
  '/(app)/klassen/$klassenId/tests': typeof appKlassenKlassenIdTestsRoute
  '/(app)/schueler/$schuelerId/anwesenheiten': typeof appSchuelerSchuelerIdAnwesenheitenRoute
  '/(app)/schueler/$schuelerId/brett': typeof appSchuelerSchuelerIdBrettRoute
  '/(app)/schueler/$schuelerId/historie': typeof appSchuelerSchuelerIdHistorieRoute
  '/(app)/schueler/$schuelerId/monitoring': typeof appSchuelerSchuelerIdMonitoringRoute
  '/(app)/diagnostikverfahren/$diagnostikId/': typeof appDiagnostikverfahrenDiagnostikIdIndexRoute
  '/(app)/ganztagsangebote/$ganztagsangebotId/': typeof appGanztagsangeboteGanztagsangebotIdIndexRoute
  '/(app)/klassen/$klassenId/': typeof appKlassenKlassenIdIndexRoute
  '/(app)/schueler/$schuelerId/': typeof appSchuelerSchuelerIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostikverfahren'
    | '/ganztagsangebote'
    | '/klassen'
    | '/reset-password'
    | '/rollenmanagement'
    | '/schueler'
    | '/settings'
    | '/login'
    | '/register'
    | '/ganztagsangebote/$ganztagsangebotId/edit'
    | '/klassen/$klassenId/brett'
    | '/klassen/$klassenId/edit'
    | '/klassen/$klassenId/tests'
    | '/schueler/$schuelerId/anwesenheiten'
    | '/schueler/$schuelerId/brett'
    | '/schueler/$schuelerId/historie'
    | '/schueler/$schuelerId/monitoring'
    | '/diagnostikverfahren/$diagnostikId'
    | '/ganztagsangebote/$ganztagsangebotId'
    | '/klassen/$klassenId'
    | '/schueler/$schuelerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostikverfahren'
    | '/ganztagsangebote'
    | '/klassen'
    | '/reset-password'
    | '/rollenmanagement'
    | '/schueler'
    | '/settings'
    | '/login'
    | '/register'
    | '/ganztagsangebote/$ganztagsangebotId/edit'
    | '/klassen/$klassenId/brett'
    | '/klassen/$klassenId/edit'
    | '/klassen/$klassenId/tests'
    | '/schueler/$schuelerId/anwesenheiten'
    | '/schueler/$schuelerId/brett'
    | '/schueler/$schuelerId/historie'
    | '/schueler/$schuelerId/monitoring'
    | '/diagnostikverfahren/$diagnostikId'
    | '/ganztagsangebote/$ganztagsangebotId'
    | '/klassen/$klassenId'
    | '/schueler/$schuelerId'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/diagnostikverfahren/'
    | '/(app)/ganztagsangebote/'
    | '/(app)/klassen/'
    | '/(app)/reset-password/'
    | '/(app)/rollenmanagement/'
    | '/(app)/schueler/'
    | '/(app)/settings/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(app)/ganztagsangebote/$ganztagsangebotId/edit'
    | '/(app)/klassen/$klassenId/brett'
    | '/(app)/klassen/$klassenId/edit'
    | '/(app)/klassen/$klassenId/tests'
    | '/(app)/schueler/$schuelerId/anwesenheiten'
    | '/(app)/schueler/$schuelerId/brett'
    | '/(app)/schueler/$schuelerId/historie'
    | '/(app)/schueler/$schuelerId/monitoring'
    | '/(app)/diagnostikverfahren/$diagnostikId/'
    | '/(app)/ganztagsangebote/$ganztagsangebotId/'
    | '/(app)/klassen/$klassenId/'
    | '/(app)/schueler/$schuelerId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)",
        "/(auth)/login/",
        "/(auth)/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/diagnostikverfahren/",
        "/(app)/ganztagsangebote/",
        "/(app)/klassen/",
        "/(app)/reset-password/",
        "/(app)/rollenmanagement/",
        "/(app)/schueler/",
        "/(app)/settings/",
        "/(app)/ganztagsangebote/$ganztagsangebotId/edit",
        "/(app)/klassen/$klassenId/brett",
        "/(app)/klassen/$klassenId/edit",
        "/(app)/klassen/$klassenId/tests",
        "/(app)/schueler/$schuelerId/anwesenheiten",
        "/(app)/schueler/$schuelerId/brett",
        "/(app)/schueler/$schuelerId/historie",
        "/(app)/schueler/$schuelerId/monitoring",
        "/(app)/diagnostikverfahren/$diagnostikId/",
        "/(app)/ganztagsangebote/$ganztagsangebotId/",
        "/(app)/klassen/$klassenId/",
        "/(app)/schueler/$schuelerId/"
      ]
    },
    "/(app)/diagnostikverfahren/": {
      "filePath": "(app)/diagnostikverfahren/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/ganztagsangebote/": {
      "filePath": "(app)/ganztagsangebote/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/klassen/": {
      "filePath": "(app)/klassen/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/reset-password/": {
      "filePath": "(app)/reset-password/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/rollenmanagement/": {
      "filePath": "(app)/rollenmanagement/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/schueler/": {
      "filePath": "(app)/schueler/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/settings/": {
      "filePath": "(app)/settings/index.tsx",
      "parent": "/(app)"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/register/": {
      "filePath": "(auth)/register/index.tsx"
    },
    "/(app)/ganztagsangebote/$ganztagsangebotId/edit": {
      "filePath": "(app)/ganztagsangebote/$ganztagsangebotId/edit.tsx",
      "parent": "/(app)"
    },
    "/(app)/klassen/$klassenId/brett": {
      "filePath": "(app)/klassen/$klassenId/brett.tsx",
      "parent": "/(app)"
    },
    "/(app)/klassen/$klassenId/edit": {
      "filePath": "(app)/klassen/$klassenId/edit.tsx",
      "parent": "/(app)"
    },
    "/(app)/klassen/$klassenId/tests": {
      "filePath": "(app)/klassen/$klassenId/tests.tsx",
      "parent": "/(app)"
    },
    "/(app)/schueler/$schuelerId/anwesenheiten": {
      "filePath": "(app)/schueler/$schuelerId/anwesenheiten.tsx",
      "parent": "/(app)"
    },
    "/(app)/schueler/$schuelerId/brett": {
      "filePath": "(app)/schueler/$schuelerId/brett.tsx",
      "parent": "/(app)"
    },
    "/(app)/schueler/$schuelerId/historie": {
      "filePath": "(app)/schueler/$schuelerId/historie.tsx",
      "parent": "/(app)"
    },
    "/(app)/schueler/$schuelerId/monitoring": {
      "filePath": "(app)/schueler/$schuelerId/monitoring.tsx",
      "parent": "/(app)"
    },
    "/(app)/diagnostikverfahren/$diagnostikId/": {
      "filePath": "(app)/diagnostikverfahren/$diagnostikId/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/ganztagsangebote/$ganztagsangebotId/": {
      "filePath": "(app)/ganztagsangebote/$ganztagsangebotId/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/klassen/$klassenId/": {
      "filePath": "(app)/klassen/$klassenId/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/schueler/$schuelerId/": {
      "filePath": "(app)/schueler/$schuelerId/index.tsx",
      "parent": "/(app)"
    }
  }
}
ROUTE_MANIFEST_END */
